# =============================================================================
# gbif/ipt
#
# IPT server by GBIF
# Modification: TODO: style similarly to rest of CIOOS Atlantic WordPress
# Example (source): https://github.com/gbif/ipt/blob/master/package/docker/Dockerfile
# =============================================================================
FROM gbif/ipt
LABEL maintainer="Jacob Thompson <jacob.thompson@wiwasolvet.ca>"

EXPOSE 8080
CMD ["catalina.sh", "run"]
